# Generated by Django 5.2.8 on 2026-01-10 12:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Client Name"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Company Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="Contact Number"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Quotation Number",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Quotation Date"),
                ),
                (
                    "validity_period",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days this quotation is valid",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Validity Period (Days)",
                    ),
                ),
                (
                    "point_of_contact",
                    models.CharField(
                        help_text="Sales person or contact person name",
                        max_length=200,
                        verbose_name="Point of Contact",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="quotations.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("modified", "Modified"),
                            ("docx_generated", "DOCX Generated"),
                            ("pdf_generated", "PDF Generated"),
                            ("email_sent", "Email Sent"),
                            ("status_changed", "Status Changed"),
                            ("downloaded", "Downloaded"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed information about what changed",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "additional_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Metadata"
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="quotations.quotation",
                        verbose_name="Quotation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Audit Log",
                "verbose_name_plural": "Quotation Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_description",
                    models.CharField(
                        choices=[
                            (
                                "storage_charges",
                                "Storage Charges (per pallet per month)",
                            ),
                            ("inbound_handling", "Inbound Handling (per unit)"),
                            ("outbound_handling", "Outbound Handling (per unit)"),
                            ("pick_pack", "Pick & Pack (per order)"),
                            ("packaging_material", "Packaging Material"),
                            ("labelling_services", "Labelling Services"),
                            (
                                "wms_platform",
                                "WMS Platform Access (monthly per pallet)",
                            ),
                            ("value_added", "Value-Added Services"),
                        ],
                        max_length=100,
                        verbose_name="Item Description",
                    ),
                ),
                (
                    "custom_description",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom description override",
                        max_length=500,
                        null=True,
                        verbose_name="Custom Description",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Unit Cost (₹)",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                        verbose_name="Quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Item",
                "verbose_name_plural": "Quotation Items",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
