# Generated by Django 5.2.8 on 2026-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.CharField(
                help_text="Enter quantity or 'at actual'",
                max_length=50,
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit_cost",
            field=models.CharField(
                help_text="Enter amount or 'as applicable'",
                max_length=50,
                verbose_name="Unit Cost (₹)",
            ),
        ),
    ]
