# Generated by Django 5.2.8 on 2026-01-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0002_alter_quotationitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationitem",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quotations.quotation",
                verbose_name="Quotation",
            ),
        ),
        migrations.CreateModel(
            name="QuotationLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="e.g., NCR, Bhiwandi, Mumbai",
                        max_length=100,
                        verbose_name="Location Name",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="quotations.quotation",
                        verbose_name="Quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Location",
                "verbose_name_plural": "Quotation Locations",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quotations.quotationlocation",
                verbose_name="Location",
            ),
        ),
    ]
