# Generated by Django 5.2.8

from django.db import migrations


def migrate_items_to_locations(apps, schema_editor):
    """
    Create a default location for each existing quotation
    and assign all items to that location
    """
    Quotation = apps.get_model('quotations', 'Quotation')
    QuotationLocation = apps.get_model('quotations', 'QuotationLocation')
    QuotationItem = apps.get_model('quotations', 'QuotationItem')
    
    for quotation in Quotation.objects.all():
        # Create default location for this quotation
        default_location = QuotationLocation.objects.create(
            quotation=quotation,
            location_name="Main",
            order=0
        )
        
        # Assign all items to this location
        QuotationItem.objects.filter(quotation=quotation).update(
            location=default_location
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration - not really feasible but required
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotationitem_quotation_quotationlocation_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_items_to_locations, reverse_migration),
    ]
