# Generated by Django 5.2.8 on 2026-01-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0005_client_is_active_clientaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_number",
            field=models.CharField(max_length=10, verbose_name="Contact Number"),
        ),
    ]
