# Generated by Django 5.2.8 on 2026-01-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0006_change_contact_number_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotationitem",
            name="custom_description",
        ),
    ]
