# Generated by Django 5.2.8 on 2026-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0007_remove_custom_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="storage_unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per_sqft", "per sq.ft"),
                    ("per_pallet", "per pallet"),
                    ("per_unit", "per unit"),
                    ("per_lumpsum", "per lumpsum"),
                    ("per_order", "per order"),
                ],
                default="per_pallet",
                help_text="Unit type for storage charges",
                max_length=50,
                null=True,
                verbose_name="Storage Unit Type",
            ),
        ),
    ]
