# Generated by Django 5.2.8 on 2026-01-28 11:54

from django.db import migrations


def populate_quotation_id(apps, schema_editor):
    """Populate quotation_id for items that have location_id but no quotation_id"""
    QuotationItem = apps.get_model('quotations', 'QuotationItem')
    QuotationLocation = apps.get_model('quotations', 'QuotationLocation')
    
    # Get all items with NULL quotation_id but have location_id
    items_to_fix = QuotationItem.objects.filter(
        quotation_id__isnull=True,
        location_id__isnull=False
    )
    
    fixed_count = 0
    for item in items_to_fix:
        try:
            # Get the quotation_id from the related location
            location = QuotationLocation.objects.get(id=item.location_id)
            item.quotation_id = location.quotation_id
            item.save()
            fixed_count += 1
        except QuotationLocation.DoesNotExist:
            print(f"Warning: QuotationItem {item.id} references non-existent location {item.location_id}")
    
    print(f"Fixed {fixed_count} QuotationItem records")



class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0008_quotationitem_storage_unit_type"),
    ]

    operations = [
        migrations.RunPython(populate_quotation_id, reverse_code=migrations.RunPython.noop),
    ]
