# Generated by Django 5.2.8 on 2026-01-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0009_populate_quotationitem_quotation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationitem",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quotations.quotation",
                verbose_name="Quotation",
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="storage_unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per_sqft", "per sq.ft per month"),
                    ("per_pallet", "per pallet per month"),
                    ("per_unit", "per unit per month"),
                    ("per_lumpsum", "per lumpsum per month"),
                    ("per_order", "per order per month"),
                ],
                default="per_pallet",
                help_text="Unit type for storage charges",
                max_length=50,
                null=True,
                verbose_name="Storage Unit Type",
            ),
        ),
    ]
